### ISSUE TITLE
backtest-example(second version) fails

### ISSUE THREAD

**Issue by kalaytan** [cuemacro/finmarketpy#10]
I've taken out a [second example](https://github.com/cuemacro/finmarketpy/blob/master/finmarketpy_examples/backtest_example.py#L121) into separate file from finmarketpy_examples/backtest_example.py

 Created a clean env and still getting the error.
I guess it's something to do with changes in finmarketpy/backtest/backtestengine.py 2 weeks ago.

> signals = backtest.get_porfolio_signal()   # get final signals for each series
> AttributeError: 'Backtest' object has no attribute 'get_porfolio_signal'

![image](https://cloud.githubusercontent.com/assets/4408153/22943293/f1e9e2ae-f2e4-11e6-955a-1df73242ac10.png)

**Comment by saeedamen** [comment]
Hi @kalaytan - there was a spelling mistake (get_portfolio_signal), now fixed :-)

**Comment by kalaytan** [comment]
so true. works fine now.

42f4bc25a43 fixed it.

Thank you!
